* General
  - кэшировать посты не только в памяти
  - кэш аватарок должен инвалидейтится время от времени
  - iframe/youtube
    * в post feed
    * в комментариях
  - прописать app как реагирующий на http://advaitaworld схему
  - nav drawer
  - переключатель разделов сайта
* Post Feed
  - заголовок показывать
  - блог в котором размещена бубликация (-> blogname)
  - парсинг img тэгов
  - читать далее
  - swipe from top to refresh
* Комментарии
  - список проголосовавших за пост - показывать каким-то образом
  - показывать скролл-индикатор сбоку. и в post feed.
  - увеличить line spacing, чтобы длинные посты читались лучше. Как пример для теста см пост Шайна про Учение.
    да и в комментах тоже!
  - действия по комментарию - ответить, проголосовать итд
  - доточить анимацию раскрытия веток комментов. Можно наподобие Inbox-а сделать, раскрытие такое вертикальное
  - когда скроллируется вниз, то наверху показывать небольшой тулбарчик типа "|AVA| Ответы на коммент salik2..."
    сделать его таким - что он уходит постепенно вверх, а если потом скорллируется вверх, а не вниз - снова показывается
    (ну как это в google+ и проч)
  - если подряд идут два коммента от одного автора, то мержить их. Тут две возможности
    * когда автор ответил сам себе: парент-дитё - от одного автора
    * когда автор ответил на родительский коммент и тут же ответил на него же: два sibling-а от одного автора
  - поподробнее потестировать случай выкачивания аватарок начисто:
    бывает, когда выкачиваются аватарки под постом, и открыть если ветку комментариев, то
    она тоже начнёт выкачивать аватарки - и может возникнуть БД-конфликт, когда обе активити
    выкачают одну и ту же аватарку и попытаются её в базу сохранить, UNIQUE constraint будет
    нарушена, будет exception
  - сделать удобство - когда долго держишь на "+3 комментария" (или другой какой триггер) выезжает списочек имён,
    которые в этой ветке комментировали дальше
  - swipe from top to refresh
